### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by ciancrobbo** [FlasHRender/Zenbook-S-UX391UA-hackintosh#3]
Hey there great work, I’m assuming you’ve stopped working on this or at least don’t have time atm. Would you be able to point me in the right direction on how I might fix the keyboard backlight on the Big Sur branch? Just a starting point would be great.

**Comment by thalatamsainath** [comment]
Hi! I still have the device so I will update it more often. I had stopped updating it because everything was sorta working. Anyways, I have pushed an update, could you try it and let me know? I have reverted back to old AsusSMC which would allow backlight, but we lose the battery charge limiter. I will check and fix it properly but till then this should work. 

If everything works, I'll close this issue.

**Comment by ciancrobbo** [comment]
Thanks for the continued support, I've tested the changes and merged them with my own plist in order to retain my SMBIOS. Looks like the keyboard won't toggle but I'm unclear on whether this as much functionality as we're going to get and asking for toggle is too much for a hack!

**Comment by thalatamsainath** [comment]
Do you mean Trackpad disable key(F6)? I had to sacrifice/reassign that to enable lowering of keyboard brightness.

**Comment by ciancrobbo** [comment]
I feel like a fool, didn't realise it was mapped as up/down not toggle.
Thanks!
